EXTENSION_MAP = {
    'jpg': 'JPEG image',
    'jpeg': 'JPEG image',
    'png': 'PNG image',
    'gif': 'GIF image',
    'bmp': 'Bitmap image (BMP)',
    'tiff': 'TIFF image (LE)',
    'tif': 'TIFF image (LE)',
    'pdf': 'PDF document',
    'zip': 'ZIP archive',
    'rar': 'RAR archive v1',
    'gz': 'GZIP compressed file',
    '7z': '7-Zip archive',
    'mp3': 'MP3 (ID3 tagged)',
    'mp4': 'MP4 video',
    'mkv': 'MKV / WebM container',
    'avi': 'RIFF container (AVI/WAV distinction needed)',
    'wav': 'RIFF container (AVI/WAV distinction needed)',
    'exe': 'PE executable (Windows EXE/DLL)',
    'dll': 'PE executable (Windows EXE/DLL)',
    'elf': 'ELF executable',
    'sqlite': 'SQLite database',
    'xml': 'XML document',
    'html': 'HTML document',
}
